# Generated by Django 2.1.7 on 2019-06-19 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=100)),
                ('description', models.CharField(default='Description', max_length=1000)),
                ('link', models.CharField(default='Link', max_length=200)),
            ],
        ),
    ]
